openapi: 3.0.1
info:
  title: Crime Data API
  description: API for fetching crime data in various cities.
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /crimes:
    get:
      summary: Get all recent crimes in Helsingborg
      responses:
        200:
          description: A list of crime events

  /crimes/locations:
    get:
      summary: Get only the crime locations
      responses:
        200:
          description: A list of crime locations

  /crimes/search:
    get:
      summary: Search for crimes in a specific city
      parameters:
        - in: query
          name: city
          schema:
            type: string
          description: The city to search for crimes
          required: true
      responses:
        200:
          description: A list of crimes for the specified city

  /crimes/latest:
    get:
      summary: Get the latest crime event
      responses:
        200:
          description: The most recent crime event
